iupac_codes = {
    "A": "Adenine",
    "C": "Cytosine",
    "G": "Guanine",
    "T": set(["T", "U"]),
    "U": set(["T", "U"]),
    "R": set(['A' , 'G']),
    "Y": set(['C' , 'T']),
    "S": set(['G' , 'C']),
    "W": set(['A' , 'T']),
    "K": set(['G' , 'T']),
    "M": set(['A' , 'C']),
    "B": set(['C' , 'G', 'T']),
    "D": set(['A' , 'G', 'T']),
    "H": set(['A' ,'C' , 'T']),
    "V": set(['A' , 'C' , 'G']),
    "N": set(['A' , 'C' , 'G', 'T']),
    ".": "gap",
    "-": "gap",
}